Battle.create(question_text: "1+1" ,possible_answers: [1,2,3,4], correct_answer: 2)
Battle.create(question_text: "2+2" ,possible_answers: [1,2,3,4], correct_answer: 4)
Battle.create(question_text: "3+3" ,possible_answers: [6,2,3,4], correct_answer: 6)
Battle.create(question_text: "4+4" ,possible_answers: [1,2,8,4], correct_answer: 8)
Battle.create(question_text: "5+5" ,possible_answers: [1,2,10,4], correct_answer: 10)